FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* yarn.lock* ./

COPY public ./public

RUN npm install

COPY . .

# Expose Storybook port
EXPOSE 6006

# Start Storybook server
CMD ["npm", "run", "storybook"]